# Generated by Django 3.2.7 on 2021-09-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210925_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
