# Generated by Django 3.2.7 on 2021-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comentario'),
        ),
    ]
